# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RasterStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layername', models.CharField(max_length=255)),
                ('raw_location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layername', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('raw_location', models.TextField()),
            ],
        ),
    ]
