# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterstore',
            name='color_location',
            field=models.TextField(blank=True),
        ),
    ]
